/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/UI/BaseButton/BaseButton.vue')['default']
    BaseCheckBox: typeof import('./src/components/UI/BaseCheckBox/BaseCheckBox.vue')['default']
    BaseInput: typeof import('./src/components/UI/BaseInput/BaseInput.vue')['default']
    BaseLink: typeof import('./src/components/UI/BaseLink/BaseLink.vue')['default']
    BaseRadio: typeof import('./src/components/UI/BaseRadio/BaseRadio.vue')['default']
    QuizCard: typeof import('./src/components/QuizCard/QuizCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
